name: Cloudflare SpeedTest Automation

on:
  schedule:
    # 每天 UTC 时间 0 点运行（北京时间 8 点）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  run-speedtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 关键：启用持久化凭证

      - name: Install CloudflareSpeedTest
        run: |
          wget -N https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_amd64.tar.gz
          tar -zxvf CloudflareST_linux_amd64.tar.gz
          chmod +x CloudflareST

      - name: Run SpeedTest
        run: |
          # 执行测速，生成 CSV 文件
          ./CloudflareST -tll 30 -tl 120 -dn 100 -sl 6 -url "https://speed.cloudflare.com/__down?bytes=10000000"

      - name: Commit and Push Results
        run: |
          git config --global user.name "Tomoe233"
          git config --global user.email "1429521105@qq.com"
          mv result.csv results/
          git add results/
          # 设置时区为上海（UTC+8）
          export TZ=Asia/Shanghai
          git commit -m "Auto-Update SpeedTest Results: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:main
